2024-09-14 17:11:46,320 INFO    MainThread:2397795 [wandb_setup.py:_flush():77] Current SDK version is 0.17.9
2024-09-14 17:11:46,321 INFO    MainThread:2397795 [wandb_setup.py:_flush():77] Configure stats pid to 2397795
2024-09-14 17:11:46,321 INFO    MainThread:2397795 [wandb_setup.py:_flush():77] Loading settings from /home/yuvalzehavi1/.config/wandb/settings
2024-09-14 17:11:46,321 INFO    MainThread:2397795 [wandb_setup.py:_flush():77] Loading settings from /home/yuvalzehavi1/Repos/multi-classification-NAM/wandb/settings
2024-09-14 17:11:46,321 INFO    MainThread:2397795 [wandb_setup.py:_flush():77] Loading settings from environment variables: {'api_key': '***REDACTED***'}
2024-09-14 17:11:46,321 INFO    MainThread:2397795 [wandb_setup.py:_flush():77] Applying setup settings: {'_disable_service': False}
2024-09-14 17:11:46,321 INFO    MainThread:2397795 [wandb_setup.py:_flush():77] Inferring run settings from compute environment: {'program_relpath': 'run_model.py', 'program_abspath': '/home/yuvalzehavi1/Repos/multi-classification-NAM/run_model.py', 'program': 'run_model.py'}
2024-09-14 17:11:46,321 INFO    MainThread:2397795 [wandb_setup.py:_flush():77] Applying login settings: {}
2024-09-14 17:11:46,322 INFO    MainThread:2397795 [wandb_init.py:_log_setup():524] Logging user logs to /home/yuvalzehavi1/Repos/multi-classification-NAM/wandb/run-20240914_171146-futd9b23/logs/debug.log
2024-09-14 17:11:46,322 INFO    MainThread:2397795 [wandb_init.py:_log_setup():525] Logging internal logs to /home/yuvalzehavi1/Repos/multi-classification-NAM/wandb/run-20240914_171146-futd9b23/logs/debug-internal.log
2024-09-14 17:11:46,322 INFO    MainThread:2397795 [wandb_init.py:init():608] calling init triggers
2024-09-14 17:11:46,322 INFO    MainThread:2397795 [wandb_init.py:init():615] wandb.init called with sweep_config: {}
config: {'dataset': <torch.utils.data.dataset.TensorDataset object at 0x7fe3b9fdcfa0>, 'num_workers': 0, 'prefetch_factor': None, 'pin_memory': False, 'pin_memory_device': '', 'timeout': 0, 'worker_init_fn': None, '_DataLoader__multiprocessing_context': None, '_dataset_kind': 0, 'batch_size': 1024, 'drop_last': False, 'sampler': <torch.utils.data.sampler.RandomSampler object at 0x7fe3b9fdce20>, 'batch_sampler': <torch.utils.data.sampler.BatchSampler object at 0x7fe3b9fdcee0>, 'generator': None, 'collate_fn': <function default_collate at 0x7fe3c1d92c10>, 'persistent_workers': False, '_DataLoader__initialized': True, '_IterableDataset_len_called': None, '_iterator': None}
2024-09-14 17:11:46,322 INFO    MainThread:2397795 [wandb_init.py:init():658] starting backend
2024-09-14 17:11:46,323 INFO    MainThread:2397795 [wandb_init.py:init():662] setting up manager
2024-09-14 17:11:46,325 INFO    MainThread:2397795 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-09-14 17:11:46,328 INFO    MainThread:2397795 [wandb_init.py:init():670] backend started and connected
2024-09-14 17:11:46,331 ERROR   MainThread:2397795 [wandb_init.py:init():1239] error in wandb.init()
Traceback (most recent call last):
  File "/home/yuvalzehavi1/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1229, in init
    return wi.init()
  File "/home/yuvalzehavi1/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 675, in init
    run = Run(
  File "/home/yuvalzehavi1/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 602, in __init__
    self._init(
  File "/home/yuvalzehavi1/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 720, in _init
    self._config._update(config, ignore_locked=True)
  File "/home/yuvalzehavi1/.local/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 180, in _update
    sanitized = self._sanitize_dict(
  File "/home/yuvalzehavi1/.local/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 267, in _sanitize_dict
    k, v = self._sanitize(k, v, allow_val_change)
  File "/home/yuvalzehavi1/.local/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 285, in _sanitize
    val = json_friendly_val(val)
  File "/home/yuvalzehavi1/.local/lib/python3.8/site-packages/wandb/util.py", line 667, in json_friendly_val
    val, _ = json_friendly(val)
  File "/home/yuvalzehavi1/.local/lib/python3.8/site-packages/wandb/util.py", line 606, in json_friendly
    obj = obj.data
AttributeError: 'TensorDataset' object has no attribute 'data'
2024-09-14 17:11:47,620 WARNING MsgRouterThr:2397795 [router.py:message_loop():77] message_loop has been closed
